# Generated by Django 4.1.5 on 2023-01-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveBigIntegerField(blank=True, max_length=9, null=True),
        ),
    ]
