# Generated by Django 4.1.5 on 2023-03-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
