# Generated by Django 4.1.5 on 2023-03-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_ruc'),
    ]

    operations = [
        migrations.CreateModel(
            name='razonSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=50)),
            ],
        ),
    ]
