# Generated by Django 4.1.5 on 2023-01-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='salidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orden', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cobras', models.PositiveIntegerField()),
                ('cargadores', models.PositiveIntegerField()),
                ('handsfree', models.PositiveIntegerField()),
                ('cascos', models.PositiveIntegerField()),
                ('repetidoras', models.PositiveIntegerField()),
                ('estaciones', models.PositiveIntegerField()),
            ],
        ),
    ]
