# Generated by Django 4.1.5 on 2023-01-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidas',
            name='cargadores',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='cascos',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='cobras',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='estaciones',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='handsfree',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='repetidoras',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
