# Generated by Django 4.1.5 on 2023-01-29 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_alter_salidas_cargadores_alter_salidas_cascos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='salidas',
            new_name='salidasDetalle',
        ),
    ]
