# Generated by Django 4.1.5 on 2023-01-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_rename_salidas_salidasdetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoRadios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
