# Generated by Django 4.1.5 on 2023-01-29 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0004_tiporadios'),
    ]

    operations = [
        migrations.CreateModel(
            name='movimientoRadios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_salida', models.PositiveIntegerField()),
                ('serial', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=15)),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movimientos.tiporadios')),
            ],
        ),
    ]
