# Generated by Django 4.1.5 on 2023-01-30 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0005_movimientoradios'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoradios',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
