# Generated by Django 4.1.5 on 2023-02-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0006_movimientoradios_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='invSeriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
            ],
        ),
    ]
