# Generated by Django 4.1.5 on 2023-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0007_invseriales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invseriales',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
