# Generated by Django 4.1.5 on 2023-02-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0008_alter_invseriales_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoRadios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
    ]
