# Generated by Django 4.1.5 on 2023-02-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0009_estadoradios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoradios',
            name='estado',
            field=models.CharField(max_length=15),
        ),
    ]
