# Generated by Django 4.1.5 on 2023-02-09 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0010_alter_estadoradios_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='invseriales',
            name='id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='movimientos.estadoradios'),
            preserve_default=False,
        ),
    ]
