# Generated by Django 4.1.5 on 2023-02-09 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0011_invseriales_id_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='invSeriales1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movimientos.estadoradios')),
            ],
        ),
    ]
