# Generated by Django 4.1.5 on 2023-02-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0012_invseriales1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='invSeriales1',
        ),
    ]
