# Generated by Django 4.1.5 on 2023-02-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0013_delete_invseriales1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invseriales',
            old_name='id_estado',
            new_name='estado',
        ),
    ]
