# Generated by Django 4.1.5 on 2023-02-09 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0014_rename_id_estado_invseriales_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='invseriales',
            name='tipo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='movimientos.tiporadios'),
            preserve_default=False,
        ),
    ]
