# Generated by Django 4.1.5 on 2023-03-08 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_telefono'),
        ('movimientos', '0015_invseriales_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='entradaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_salida', models.PositiveIntegerField()),
                ('id_orden', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cobras', models.PositiveIntegerField(null=True)),
                ('cargadores', models.PositiveIntegerField(null=True)),
                ('handsfree', models.PositiveIntegerField(null=True)),
                ('cascos', models.PositiveIntegerField(null=True)),
                ('repetidoras', models.PositiveIntegerField(null=True)),
                ('estaciones', models.PositiveIntegerField(null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
            ],
        ),
    ]
