# Generated by Django 4.1.5 on 2023-03-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0016_entradadetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidasdetalle',
            name='baterias',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
