# Generated by Django 4.1.5 on 2023-03-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0017_salidasdetalle_baterias'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadetalle',
            name='baterias',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
