# Generated by Django 4.1.5 on 2023-03-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0018_entradadetalle_baterias'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesoriosFaltantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_salida', models.PositiveIntegerField()),
                ('fcobras', models.PositiveIntegerField(null=True)),
                ('fbaterias', models.PositiveIntegerField(null=True)),
                ('fcargadores', models.PositiveIntegerField(null=True)),
                ('fhandsfree', models.PositiveIntegerField(null=True)),
                ('fcascos', models.PositiveIntegerField(null=True)),
                ('frepetidoras', models.PositiveIntegerField(null=True)),
                ('festaciones', models.PositiveIntegerField(null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
