# Generated by Django 4.1.5 on 2023-03-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0020_radiosfantantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadetalle',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
    ]
