# Generated by Django 4.1.5 on 2023-01-26 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('estadoOrden', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('fecha_evento', models.DateField()),
                ('fecha_retiro', models.DateField()),
                ('cantidad_radios', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_cobras', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_baterias', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_cargadores', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_manoslibros', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_cascos', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_repetidoras', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_radio_estac', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('direccion_entrega', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estadoOrden.estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
