# Generated by Django 4.1.5 on 2023-01-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_rename_cantidad_manoslibros_orden_cantidad_manos_libres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='cantidad_radio_estac',
            new_name='cantidad_estaciones',
        ),
    ]
