# Generated by Django 4.1.5 on 2023-02-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_rename_cantidad_radio_estac_orden_cantidad_estaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='user',
        ),
    ]
