# Generated by Django 4.1.5 on 2023-02-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_telefono'),
        ('estadoOrden', '0001_initial'),
        ('ordenes', '0004_remove_orden_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordenRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('fecha_evento', models.DateField()),
                ('fecha_retiro', models.DateField()),
                ('cantidad_radios', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_cobras', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_baterias', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_cargadores', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_manos_libres', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_cascos', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_repetidoras', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_estaciones', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('direccion_entrega', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estadoOrden.estado')),
            ],
        ),
    ]
