# Generated by Django 4.1.5 on 2023-03-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_ordenregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenregistro',
            name='cantidad_baterias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordenregistro',
            name='cantidad_cargadores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordenregistro',
            name='cantidad_cascos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordenregistro',
            name='cantidad_cobras',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordenregistro',
            name='cantidad_estaciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordenregistro',
            name='cantidad_manos_libres',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordenregistro',
            name='cantidad_radios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordenregistro',
            name='cantidad_repetidoras',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
