# Generated by Django 4.1.5 on 2023-03-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_alter_ordenregistro_cantidad_baterias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenregistro',
            old_name='fecha_evento',
            new_name='fecha_evento_desde',
        ),
        migrations.AddField(
            model_name='ordenregistro',
            name='fecha_evento_hasta',
            field=models.DateField(null=True),
        ),
    ]
