# Generated by Django 4.1.5 on 2023-03-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_alter_ordenregistro_fecha_evento_hasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
            ],
        ),
    ]
