# Generated by Django 4.1.5 on 2023-03-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_alias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alias',
        ),
    ]
