# Generated by Django 4.1.5 on 2023-03-10 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_razonsocial'),
        ('ordenes', '0010_delete_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenregistro',
            name='razon_Social',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.razonsocial'),
            preserve_default=False,
        ),
    ]
