# Generated by Django 4.1.5 on 2023-03-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_razonsocial'),
        ('ordenes', '0011_ordenregistro_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenregistro',
            name='razon_Social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.razonsocial'),
        ),
    ]
